# Generated by Django 5.0 on 2025-09-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=120, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('insights', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_found', models.BooleanField(default=False)),
                ('email_validated', models.BooleanField(default=False)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_title', models.CharField(blank=True, max_length=255, null=True)),
                ('personalized_message', models.TextField(blank=True, null=True)),
                ('lead_score', models.IntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('extracted_signals', models.JSONField(blank=True, null=True)),
                ('website_signals', models.JSONField(default=dict, help_text='Signals extracted from website content')),
                ('hardware_mentions', models.JSONField(default=list, help_text='List of hardware-related terms found')),
                ('tech_stack', models.JSONField(default=list, help_text='Detected technology stack')),
                ('source', models.CharField(default='mock', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('enriched', 'Enriched'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_log', models.JSONField(default=list, help_text='List of errors during enrichment')),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('domain', 'source'), name='unique_domain_source'),
        ),
    ]
